name: bot3
on: [push]

jobs:
  run-bot1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install python-telegram-bot gTTS
      - name: Run bot
        run: python bot3.py
